kid:
  name : Rayhaan
shop:
  name : ${kid.name} reed centre
  
list:
  name : Rayhaan, Rakhaa, Hussain, Asleena, Raja, Meharoonisha, Mountain
db:
  config : "{dbname : 'localhost', userName : 'ussain', password : 'passwordfromcloud'}"
  name : mysqlwe
  port : 8976
  pool : true
  