kid:
  name : Rakhaa
shop:
  name : ${kid.name} reed centre
  
list:
  name : Rayhaan, Rakhaa, Huin, Asleena, Raja, Meharoonisha, Mountain, Ammapet, Salem
db:
  config : "{dbname : 'localhost', userName : 'ussain', password : 'passwordfromcloud'}"
  name : mysqlwe
  port : 8976
  pool : false
  pwd  : yes
